swagger: "2.0"
info:
  version: "1.0.0"
  title: "Bookshare"
host: "bookshare.swagger.io"
basePath: "/v2"
tags:
  - name: "book"
    description: "Single book operations"
  - name: "books"
    description: "Collection of books operation"
  - name: "library"
    description: "Operations to be done for the libraries"
schemes:
  - "https"
  - "http"
paths:
  /book:
    post:
      tags:
        - "book"
      summary: "Adds a new book to a library"
      description: ""
      operationId: "addBook"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Data of the book to be added"
          required: true
          schema:
            $ref: "#/definitions/BookCreationRequest"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/BookCreationResponse"
        405:
          description: "Invalid input"
    put:
      tags:
        - "book"
      summary: "Modifies a book of the library"
      description: ""
      operationId: "modifyBook"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Data of the book to be modified"
          required: true
          schema:
            $ref: "#/definitions/BookCreationRequest"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/BookCreationResponse"
        405:
          description: "Invalid input"
  /books:
    get:
      tags:
        - "books"
      summary: "Gets the list of available books"
      description: ""
      operationId: "getBooks"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Data of the book to be added"
          required: true
          schema:
            $ref: "#/definitions/BookCreationRequest"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/BookCreationResponse"
        405:
          description: "Invalid input"
  /group:
    post:
      tags:
        - "group"
      summary: "Adds a new group of libraries"
      description: ""
      operationId: "addGroup"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Property id and contact of the new library"
          required: true
          schema:
            $ref: "#/definitions/GroupCreationRequest"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/GroupCreationResponse"
        405:
          description: "Invalid input"
  /library:
    post:
      tags:
        - "library"
      summary: "Adds a new library"
      description: ""
      operationId: "addLibrary"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Property id and contact of the new library"
          required: true
          schema:
            $ref: "#/definitions/LibraryCreationRequest"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/LibraryCreationResponse"
        405:
          description: "Invalid input"

definitions:
  BookCreationRequest:
    type: "object"
    properties:
      id:
        type: "string"

  BookCreationResponse:
    type: "object"
    properties:
      id:
        type: "string"

  GroupCreationRequest:
    type: "object"
    properties:
      name:
        type: "string"
      location:
        $ref: "#/definitions/Location"
      adminId:
        type: "string"

  GroupCreationResponse:
    type: "object"
    properties:
      id:
        type: "string"

  LibraryCreationRequest:
    type: "object"
    properties:
      groupId:
        type: "string"
      propertyName:
        type: "string"
      contactName:
        type: "string"
      owner:
        type: "string"

  LibraryCreationResponse:
    type: "object"
    properties:
      id:
        type: "string"

  Location:
    type: "object"
    properties:
      town:
        type: "string"
      country:
        type: "string"

securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
